test = 'pp_test_level.txt'
wai = 'hero.png'
bg1 = r'backgrounds\game-bg.png'
floor = r'textures\0-texture.png'
wallx = r'textures\#-texture.png'
wally = r'textures\=-texture.png'
lvl1 = 'pp_test_level.txt'
lvl2 = 'pp_test_level_2.txt'