import pygame

# menu sprite groups
animatedTypedText = pygame.sprite.Group()
animatedIntro = pygame.sprite.Group()
animatedHero = pygame.sprite.Group()
animatedStars = pygame.sprite.Group()
animatedDots = pygame.sprite.Group()
animatedError = pygame.sprite.Group()
animatedFight = pygame.sprite.Group()
animatedDialogue = pygame.sprite.Group()

# game sprite groups
toches = pygame.sprite.Group()
bgroup = pygame.sprite.Group()
platformgroup = pygame.sprite.Group()
characters = pygame.sprite.Group()
untouches = pygame.sprite.Group()
finale = pygame.sprite.Group()
shadowgroup = pygame.sprite.Group()
projectilesgroup = pygame.sprite.Group()
changegroup = pygame.sprite.Group()
thorngroup = pygame.sprite.Group()
breakgroup = pygame.sprite.Group()
triggergroup = pygame.sprite.Group()
sloniks = pygame.sprite.Group()
nmeprojectilesgroup = pygame.sprite.Group()
anothertoches = pygame.sprite.Group()
xwalls = pygame.sprite.Group()
ywalls = pygame.sprite.Group()
boss_group = pygame.sprite.Group()
boss_projectile_group = pygame.sprite.Group()
health_bar = pygame.sprite.Group()
hero_health = pygame.sprite.Group()
hleb = pygame.sprite.Group()
